---
abstract: 'Allows RT to do authentication via a service which supports the OpenID API'
author:
  - 'Artur Bergman <sky@crucially.net>, Jesse Vincent <jesse@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-OpenID
no_index:
  directory:
    - html
    - inc
requires:
  Cache::FileCache: 0
  LWP::UserAgent::Paranoid: 0.92
  Net::OpenID::Consumer: 1.13
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.04
